name: lint

on:
  push:
    branches:
      - main
      - next
    paths:
      - 'packages/**'

  pull_request:
    branches:
      - main
      - next
    paths:
      - 'packages/**'

jobs:
  ESLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.28.0

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm lint
