name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Code Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run ESLint
        run: pnpm lint

  test:
    name: Unit Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Cross-platform, multi-version Runtime testing
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [14, 16, 18]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run ESLint
        run: pnpm lint
      - name: Run compile and build packages
        run: pnpm build
      - name: Run tests
        run: pnpm test:unit

  coverage-report:
    name: Coverage Report
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm
        uses: pnpm/action-setup@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run compile and build packages
        run: pnpm build
      - name: Run tests and collect coverage
        run: pnpm test:coverage
      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
